version: 1.0
name: RemakeHypixelSkyblock
Authors: [OptimusChan, Itchs]
main: com.itech4kids.skyblock.Main
commands:
  sbmenu:
    description: Opens the Skyblock Main Menu.
  spawncm:
    description: Spawns a custom mob.
    aliases: [spawnmob, spawncustommob]
  setPlayerStat:
    description: Set's a player's stat.
    aliases: [setStat, stat]
  itembrowser:
    description: Opens the item browser menu.
    aliases: [ib, items]
  swordcategory:
    description: Opens the sword category in the item browser menu.
  swordcategory2:
    description: Opens the 2nd page of the Sword Category in the Item Browser menu.
  todolist:
    description: Opens the todo list menu.
    aliases: [todo]
  trade:
    description: TRADE TRADE TRADE TRADE
  skill:
    description: Set your skill to an integer
  sreforge:
    description: Adds a reforge to an item
    aliases: [sref]
  pets:
    description: TEST PETS
  recombobulate:
    description: Increases the rarity of an item by 1
    aliases: [recomb]
  rarity:
    description: Change the rarity of an item
  warp:
    description: Teleports you to your desired destination
  collections:
    description: WIP
  item:
    description: WIP
  helmetcategory:
    description: WIP
  chestplatecategory:
    description: WIP
  leggingscategory:
    description: WIP
  bootscategory:
    description: WIP
  materialscategory:
  visit:
    description: Visit other players islands
  launchpad:
    description: WIP
  wipe:
    description: Wipe a player for cheating
  mobspawn:
    aliases: [ms]
    description: Setup mob spawn locations
  ban:
  kick:
  location: